// src/components/FlowEditor/Sidebar.vue
<script setup lang="ts">
const onDragStart = (event: DragEvent, nodeType: string) => {
  if (event.dataTransfer) {
    event.dataTransfer.setData("application/vueflow", nodeType);
    event.dataTransfer.effectAllowed = "move";
  }
};
</script>

<template>
  <aside>
    <div class="description">Drag nodes to the canvas</div>
    <div class="nodes">
      <div
        class="vue-flow__node-trigger"
        :draggable="true"
        @dragstart="onDragStart($event, 'trigger')"
      >
        Trigger Node
      </div>
      <div
        class="vue-flow__node-action"
        :draggable="true"
        @dragstart="onDragStart($event, 'action')"
      >
        Action Node
      </div>
      <div
        class="vue-flow__node-condition"
        :draggable="true"
        @dragstart="onDragStart($event, 'condition')"
      >
        Condition Node
      </div>
    </div>
  </aside>
</template>

<style>
aside {
  width: 20%;
  max-width: 250px;
  background-color: var(--sidebar-bg);
  padding: 15px;
  border-right: 1px solid var(--border-color);
}

.description {
  margin-bottom: 10px;
}

.nodes > * {
  margin-bottom: 10px;
  padding: 10px;
  border-radius: 5px;
  cursor: grab;
  transition:
    transform 0.2s,
    box-shadow 0.2s;
}

.nodes > *:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 8px rgba(0 0 0 / 3%);
}
</style>

// src/components/elements/Sidebar.tsx
import { NodeData } from '@/types';

const nodeData: NodeData[] = [
  {
    type: 'trigger',
    label: 'Trigger Node',
    description: 'This is trigger node',
    outputArray: [
      {  label: 'true' },
    ],
  },
  {
    type: 'action',
    label: 'Action Node',
    description: 'This is an action node',
    outputArray: [
      {  label: 'true' },
      {  label: 'false' },
      {  label: 'true' },
      {  label: 'false' },
      {  label: 'true' },
      {  label: 'false' },
      {  label: 'true' },
      {  label: 'false' },
      {  label: 'true' },
      {  label: 'false' },
      {  label: 'true' },
      {  label: 'false' },
    ],
  },
  {
    type: 'end',
    label: 'End Node',
    description: 'This is an end node',
    outputArray: [],
  }
];

export default function Sidebar() {
  const onDragStart = (event: React.DragEvent, nodeData:NodeData) => {
    event.dataTransfer.setData('application/reactflow', JSON.stringify(nodeData));
    event.dataTransfer.effectAllowed = 'move';
  };

  return (
    <aside className="w-64 bg-gray-100 p-4">
      <div className="text-xl font-bold mb-4">Node Types</div>
      <div className="flex flex-col gap-4">
        {
          nodeData?.map((arr, id)=>(
        <div
        key={id}
        className="bg-white p-4 rounded-md shadow cursor-move"
        onDragStart={(event) =>
          onDragStart(event, arr)
        }
        draggable
      >
        {arr?.type}
      </div>
          )
          )
        }
      </div>
    </aside>
  );
}
